version: '3'
services:
    redis:
      image: redis:6.0.9
      container_name: redis
      command: redis-server /etc/redis.conf
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - ./redis.conf:/etc/redis.conf
        - /data/redis:/data
      # - "${REDIS_DIR}/conf:/usr/local/etc/redis"
      #  - "${REDIS_DIR}/data:/data"

    mysql:
      image: mysql:5.6
      container_name: mysql
      ports:
        - 9910:3306
    #volumes:
    #  - "${MYSQL_DIR}/data:/var/lib/mysql"
    #  - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
      environment:
        # 环境变量
        - MYSQL_DATABASE=gorm
        - MYSQL_USER=gorm
        - MYSQL_PASSWORD=gorm
        - MYSQL_RANDOM_ROOT_PASSWORD="yes"